apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  jwtsecret: dGhpc2lzdGhlY2hhdHByb2plY3Q=
  mongoDB1UserName: ZmFiaWFu
  mongoDB1Password: MTIzNDU=
  mongoDB1URI: bW9uZ29kYjovL2ZhYmlhbjoxMjM0NUBtb25nb2RiMToyNzAxNy9teWRhdGFiYXNlP2F1dGhTb3VyY2U9YWRtaW4=
  mongoDB2UserName: ZmFiaWFu
  mongoDB2Password: MTIzNDU=
  mongoDB2URI: bW9uZ29kYjovL2ZhYmlhbjoxMjM0NUBtb25nb2RiMjoyNzAxNy9teWRhdGFiYXNlP2F1dGhTb3VyY2U9YWRtaW4=
  mongoDB3UserName: ZmFiaWFu
  mongoDB3Password: MTIzNDU=
  mongoDB3URI: bW9uZ29kYjovL2ZhYmlhbjoxMjM0NUBtb25nb2RiMzoyNzAxNy9teWRhdGFiYXNlP2F1dGhTb3VyY2U9YWRtaW4=